import { Router } from 'express'
import { Quote } from 'src/stores/quote-store'
import { generateQuoteListData, generateFodderQuote } from '../data/quote.data'

function generateReceives() {
  const RECEIVE_COUNT = 30
  const UNIQUE_USER_COUNT = 10
  const receives: { id: string; userId: string }[] = []

  for (let receiveNo = 1; receiveNo <= RECEIVE_COUNT; receiveNo++) {
    receives.push({
      id: `receive-${receiveNo}`,
      userId: `user-${receiveNo % UNIQUE_USER_COUNT || UNIQUE_USER_COUNT}`,
    })
  }

  return receives
}

const QUOTE_LIST_DATA = generateQuoteListData(100)

export function serverQuotesController(app: Router) {
  const router = Router()

  router.get('/server/:serverId/quote', (req, res) => {
    const { cursorId, count } = req.query
    const parsedCount = Number(count || 10)

    if (!cursorId) {
      res.json(QUOTE_LIST_DATA.slice(0, parsedCount))
    } else {
      const idx = QUOTE_LIST_DATA.findIndex((id) => id === cursorId)
      res.json(QUOTE_LIST_DATA.slice(idx + 1, idx + parsedCount + 1))
    }
  })

  router.get('/server/:serverId/quote/dummy', (req, res) => {
    res.json({
      id: 'dummy',
      content:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',

      authorId: 'user-1',
      submitterId: 'user-2',

      serverId: req.params.serverId,

      receives: generateReceives(),
      status: 'ACCEPTED',
      submitDt: new Date('2022-01-01'),
    } as Quote)
  })

  router.get('/server/:serverId/quote/quote-fodder-:quoteNo', (req, res) => {
    const { serverId, quoteNo } = req.params
    const generated = generateFodderQuote(serverId, quoteNo)

    const parsedId = parseInt(quoteNo)

    // we're using this to alternate between approved and pending
    if (parsedId % 2 === 0) {
      // quotes generated by generateFodderQuote are approved by default
      return res.json(generated)
    }

    // we need to manipulate the data a bit if we want pending quotes
    generated.requiredVoteCount = 3
    generated.votes = {
      'user-1': new Date('2022-01-01'),
      'user-2': new Date('2022-01-01'),
    }
    generated.submitDt = new Date('2022-01-01')
    /*
     * Technically the quote would be expired by now since this date has passed,
     * but since we're not bothering with expired quotes for now this is good enough.
     */
    generated.expirationDt = new Date('2022-01-02')

    res.json(generated)
  })

  app.use('', router)
}
