services:
  frontend:
    # points to the root of this repository
    build: ../../.
    restart: unless-stopped
    ports:
      - 9080:80
    volumes:
      - ./templates:/etc/nginx/templates
    env_file:
      - .env
